# Generated by Django 2.2.4 on 2019-09-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorytable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
