# Generated by Django 2.2.4 on 2019-09-07 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('development', '0002_categorytable'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='development.categorytable'),
            preserve_default=False,
        ),
    ]
