# Generated by Django 2.2.4 on 2019-09-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='summary',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
